"""Adds Author model

Revision ID: 259be1cca2e1
Revises: eec17fb24a4b
Create Date: 2022-05-10 08:53:39.773064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259be1cca2e1'
down_revision = 'eec17fb24a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
